apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: manager
        image: k8scc01covidacr.azurecr.io/kubeflow/notebook-controller:0524491606c8c4477d9b2c887948a12d7660a3e4
        command:
          - /manager
        env:
          - name: ENABLE_CULLING
            value: "true"
          - name: IDLE_TIME
            value: "10080"
          - name: CULLING_CHECK_PERIOD
            value: "1"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
      serviceAccountName: service-account
