apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: manager
        image: gcr.io/kubeflow-images-public/notebook-controller:v1.1.0-gd3377cbd
        command:
          - /manager
        env:
          - name: ENABLE_CULLING
            value: "true"
          - name: IDLE_TIME
            value: "10080"
          - name: CULLING_CHECK_PERIOD
            value: "1"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
      serviceAccountName: service-account
