apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/apps/jupyter/notebook-controller/upstream/overlays/kubeflow?ref=v1.6.0

patchesStrategicMerge:
- deployment.yaml

configMapGenerator:
# Update the link to the Gateway to use.
# https://github.com/kubeflow/manifests/blob/c2795524afd97dc0776b804521bb7d937646e98f/apps/jupyter/notebook-controller/upstream/manager/kustomization.yaml#L5
- name: config
  behavior: merge
  literals:
  - ISTIO_GATEWAY=istio-system/kubeflow-istio-ingress-gateway-https
