apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/apps/jupyter/notebook-controller/upstream/overlays/kubeflow?ref=v1.6.0

patchesStrategicMerge:
- deployment.yaml

# Update the link to the Gateway to use.
configMapGenerator:
- name: config
  behavior: merge
  literals:
  - ISTIO_GATEWAY=istio-system/kubeflow-istio-ingress-gateway-https
