apiVersion: v1
kind: ConfigMap
metadata: 
  name: kubeflow-pipelines-profile-controller-env
data:
  VISUALIZATION_SERVER_IMAGE: "k8scc01covidacr.azurecr.io/kubeflow-pipeline/kubeflow-pipeline"
  FRONTEND_IMAGE: "k8scc01covidacr.azurecr.io/kubeflow-pipeline/kubeflow-pipeline"
  VISUALIZATION_SERVER_TAG: "5c41c42f"
  FRONTEND_TAG: "5c41c42f"
