apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
- service.yaml
- kubeflow-pipelines-profile-controller-env.yaml
configMapGenerator:
- name: kubeflow-pipelines-profile-controller-code
  files:
  - sync.py
  behavior: replace
resources:
- ../../../.cache/manifests/manifests-1.2-branch/pipeline/installs/multi-user/
