apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
- service.yaml
resources:
- ../../../.cache/manifests/manifests-1.2-branch/pipeline/installs/multi-user
