apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: jupyter-web-app
        imagePullPolicy: IfNotPresent
        image: k8scc01covidacr.azurecr.io/jupyter-apis:866a7c826f598231326ed36abf460e8efe36a8cc
        env:
        - name: UI
          value: default
        - name: USERID_HEADER
          value: null
          valueFrom:
            configMapKeyRef:
              name: kubeflow-config
              key: userid-header
        - name: USERID_PREFIX
          value: null
          valueFrom:
            configMapKeyRef:
              name: kubeflow-config
              key: userid-prefix
        - name: KUBECOST_URL
          value: http://kubecost-cost-analyzer.kubecost-system.svc.cluster.local:9090
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
        - name: logos-volume
          mountPath: /static/assets/group-one-icon.svg
          subPath: group-one-icon.svg
        - name: logos-volume
          mountPath: /static/assets/group-one-logo.svg
          subPath: group-one-logo.svg
        - name: logos-volume
          mountPath: /static/assets/group-two-icon.svg
          subPath: group-two-icon.svg
        - name: logos-volume
          mountPath: /static/assets/group-two-logo.svg
          subPath: group-two-logo.svg
        - name: logos-volume
          mountPath: /static/assets/jupyter-icon.svg
          subPath: jupyter-icon.svg
        - name: logos-volume
          mountPath: /static/assets/jupyterlab-logo.svg
          subPath: jupyterlab-logo.svg
        - name: logos-volume
          mountPath: /src/apps/default/static/assets/logos
      serviceAccountName: service-account
      volumes:
      - configMap:
          name: jupyter-web-app-config
        name: config-volume
      - configMap:
          name: jupyter-web-app-logos
        name: logos-volume
      imagePullSecrets:
      - name: k8scc01covidacr-registry-connection
