apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: jupyter-web-app
        imagePullPolicy: IfNotPresent
        image: k8scc01covidacr.azurecr.io/jupyter-apis:6d850d61d0862ff95e0d189a128d64b632843a33
        env:
        - name: UI
          value: default
        - name: USERID_HEADER
          value: null
          valueFrom:
            configMapKeyRef:
              name: kubeflow-config
              key: userid-header
        - name: USERID_PREFIX
          value: null
          valueFrom:
            configMapKeyRef:
              name: kubeflow-config
              key: userid-prefix
        - name: KUBECOST_URL
          value: http://kubecost-cost-analyzer.kubecost-system.svc.cluster.local:9090
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: logos-volume
          mountPath: /static/assets/logos/
      - name: nginx
        image: docker.io/nginxinc/nginx-unprivileged:1.21-alpine
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "0.25"
            memory: "250Mi"
          requests:
            cpu: "0.25"
            memory: "250Mi"
        volumeMounts:
          - name: jwa-nginx-configuration
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: static-files
            mountPath: /etc/nginx/html/
        ports:
          - name: http
            containerPort: 5000
      serviceAccountName: service-account
      initContainers:
      - name: copy-jwa-static-files
        # Change for the image I just built
        image: k8scc01covidacr.azurecr.io/jupyter-apis:6d850d61d0862ff95e0d189a128d64b632843a33
        # image: k3d-s3proxy-registry:5050/s3proxy-dev:latest
        command: [sh, -c]
        args: ["cp -r /src/dist/frontend/* /etc/nginx/html/"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /etc/nginx/html/
            name: static-files
      volumes:
        - name: jwa-nginx-configuration
          configMap:
            name: jwa-nginx-configuration
        - name: static-files
          emptyDir: {}
        - configMap:
            name: jupyter-web-app-config
          name: config-volume
        - configMap:
            name: jupyter-web-app-logos
          name: logos-volume
      imagePullSecrets:
      - name: k8scc01covidacr-registry-connection
