apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/apps/jupyter/jupyter-web-app/upstream/overlays/istio?ref=v1.4.1
- configs/kubeflow-config.yaml

patchesStrategicMerge:
- cluster-role.yaml
- deployment.yaml

configMapGenerator:
- files:
  - configs/spawner_ui_config.yaml
  behavior: replace
  name: jupyter-web-app-config
  namespace: kubeflow

generatorOptions:
  disableNameSuffixHash: true
