apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/apps/jupyter/jupyter-web-app/upstream/overlays/istio?ref=v1.6.0
- configs/kubeflow-config.yaml
- configs/nginx-config.yaml

patchesStrategicMerge:
- cluster-role.yaml
- deployment.yaml
- vs.yaml

configMapGenerator:
- files:
  - configs/spawner_ui_config.yaml
  behavior: replace
  name: jupyter-web-app-config
  namespace: kubeflow

generatorOptions:
  disableNameSuffixHash: true

patches:
  - patch: |-
      - op: replace
        path: /spec/gateways
        value: ["istio-system/kubeflow-istio-ingress-gateway-https"]
    target:
      group: networking.istio.io
      kind: VirtualService
