apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubeflow
  namespace: argocd
spec:
  generators:
  - list:
      elements:

      ## Provides ArgoCD Application Metadata for the `aaw` stack
      ##
      ##

      ## Kubeflow (common)

      - app: kubeflow-namespace
        folder: common
        version: main
      - app: kubeflow-roles
        folder: common
        version: main
      - app: oidc-authservice
        folder: common
        version: main

      ## Kubeflow (apps)

      - app: centraldashboard
        folder: apps
        version: main
      - app: katib
        folder: apps
        version: main
      - app: pipeline
        folder: apps
        version: main

  template:
    metadata:
      name: 'kubeflow-aaw'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/statcan/aaw-kubeflow-manifests.git
        targetRevision: {{version}}
        path: kustomize/{{folder}}/{{app}}/base
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
