apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

## Necessary adjustments for running the `aaw` stack on a local, dev, and CI environment
##
##

## Kubeflow (common)

- ../../common/kubeflow-namespace/
- ../../common/kubeflow-roles/
- ../../common/oidc-authservice/

## Kubeflow (apps)

- ../../apps/centraldashboard
- ../../apps/katib
- ../../apps/kfserving
- ../../apps/pipeline
