apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../.cache/manifests/manifests-1.2-branch/katib/installs/katib-standalone
images:
- name: mysql
  newName: mysql
  newTag: 8.0.22
