apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: katib
    app.kubernetes.io/name: katib-controller
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-katib-admin: "true"
  name: kubeflow-katib-edit
rules:
- apiGroups:
  - pipelines.kubeflow.org
  resources:
    - experiments
    - trials
    - suggestions
    - runs
  verbs:
    - archive
    - retry
    - get
    - list
    - watch
    - create
    - delete
    - deletecollection
    - patch
    - update
    - terminate
