apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo
rules:
  - verbs:
      - create
      - get
      - delete
      - list
      - watch
      - update
      - patch
    apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - create
      - delete
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
  - verbs:
      - get
      - list
      - watch
      - update
      - patch
    apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflows/finalizers
      - workflowtasksets
      - workflowtasksets/finalizers
      - workflowtemplates
      - workflowtemplates/finalizers
      - cronworkflows
      - cronworkflows/finalizers
  - verbs:
      - '*'
    apiGroups:
      - sparkoperator.k8s.io
    resources:
      - sparkapplications
