apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# For a detailed summary of this Kustomization please see: https://github.com/StatCan/daaas/issues/683

# https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/env/platform-agnostic-multi-user/kustomization.yaml
bases:
  - github.com/kubeflow/manifests/apps/pipeline/upstream/base/installs/multi-user?ref=v1.3.1
  - github.com/kubeflow/manifests/apps/pipeline/upstream/base/metadata/base?ref=v1.3.1
  - github.com/kubeflow/manifests/apps/pipeline/upstream/base/metadata/options/istio?ref=v1.3.1

  # https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/third-party/argo/installs/cluster/kustomization.yaml
  - github.com/argoproj/argo-workflows/manifests/base/crds?ref=v3.2.6
  - github.com/argoproj/argo-workflows/manifests/cluster-install/workflow-controller-rbac?ref=v3.2.6
  - github.com/kubeflow/manifests/apps/pipeline/upstream/third-party/argo/base?ref=v1.3.1

  - github.com/kubeflow/manifests/apps/pipeline/upstream/third-party/mysql/base?ref=v1.3.1
  - github.com/kubeflow/manifests/apps/pipeline/upstream/third-party/mysql/options/istio?ref=v1.3.1
  - github.com/kubeflow/manifests/apps/pipeline/upstream/third-party/minio/base?ref=v1.3.1
  - github.com/kubeflow/manifests/apps/pipeline/upstream/third-party/minio/options/istio?ref=v1.3.1
  - github.com/kubeflow/manifests/apps/pipeline/upstream/third-party/metacontroller/base?ref=v1.3.1

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines

# !!! If you want to customize the namespace,
# please also update base/cache-deployer/cluster-scoped/cache-deployer-clusterrolebinding.yaml
namespace: kubeflow

patchesStrategicMerge:
- ml-pipeline-ui.yaml
- workflow-controller-configmap-patch.yaml
- workflow-controller-deployment-patch.yaml

patches:
- path: ml-pipeline-config.json
  target:
    kind: Deployment
    name: ml-pipeline
    version: v1

- path: ml-pipeline-persistenceagent-config.json
  target:
    kind: Deployment
    name: ml-pipeline-persistenceagent
    version: v1

patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: argo-binding
  path: workflow-controller-clusterrolebinding-patch.json
