apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: namespace_patch.json
  target:
    kind: Namespace
    name: kubeflow
    version: v1
resources:
- github.com/kubeflow/manifests/common/kubeflow-namespace/base?ref=v1.3.1
