apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/apps/kfserving/upstream/overlays/kubeflow?ref=v1.3.1
- authorizationpolicy.yaml
- cluster-local-gateway.yaml

patchesStrategicMerge:
- inferenceservice-configmap.yaml
