apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
          # We use a patch to set the USE_ISTIO because in other patches
          # we want to set it to a configMapRef and so if we include the value
          # in the base when we do the merge we end up with 2 fields setting the value.
          - name: USE_ISTIO
            value: "false"
          - name: POD_LABELS
            value: $(POD_LABELS)
          - name: ENABLE_CULLING
            value: "true"
          - name: IDLE_TIME
            value: "1440"
          - name: CULLING_CHECK_PERIOD
            value: "1"
