apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/apps/katib/upstream/installs/katib-standalone?ref=v1.3.1
images:
- name: mysql
  newName: mysql
  newTag: 8.0.22
