apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- cluster-role.yaml
- deployment.yaml
- deployment_patch.yaml
resources:
- ../../../.cache/manifests/manifests-1.2-branch/stacks/azure/application/jupyter-web-app
configMapGenerator:
- files:
  - configs/spawner_ui_config.yaml
  behavior: replace
  name: jupyter-web-app-config
generatorOptions:
  disableNameSuffixHash: true
