apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/common/oidc-authservice/base?ref=v1.3.1

patchesStrategicMerge:
- configmap.yaml
- statefulset.yaml

patchesJson6902:
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: EnvoyFilter
    name: authn-filter
  path: envoyfilter-patch.json
