apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- github.com/kubeflow/manifests/apps/profiles/upstream/overlays/kubeflow?ref=v1.3.1

configMapGenerator:
  - name: namespace-labels-data
    files:
      - namespace-labels.yaml

patchesStrategicMerge:
- deployment.yaml
