apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/contrib/kserve/kserve?ref=v1.6.0
- authorizationpolicy.yaml
- cluster-local-gateway.yaml

patchesStrategicMerge:
- inferenceservice-configmap.yaml

## Cert Manager
patchesJson6902:
  - target:
      group: cert-manager.io
      version: v1alpha2
      kind: 'Certificate|Issuer'
      name: '.*'
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: cert-manager.io/v1
