apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/common/knative/knative-serving/base?ref=v1.3.1
- github.com/kubeflow/manifests/common/knative/knative-eventing/base?ref=v1.3.1

patchesStrategicMerge:
- config-domain.yaml

patches:
- path: istio-webhook-deployment-patch.json
  target:
    kind: Deployment
    name: istio-webhook
    version: v1

- path: webhook-deployment-patch.json
  target:
    kind: Deployment
    name: webhook
    version: v1

- path: config-istio.yaml
