apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/contrib/seldon/seldon-core-operator/base?ref=v1.6.0

## Cert Manager
patchesJson6902:
  - target:
      group: cert-manager.io
      version: v1alpha2
      kind: 'Certificate|Issuer'
      name: '.*'
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: cert-manager.io/v1

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: seldon-controller-manager
        namespace: kubeflow
      spec:
        template:
          spec:
            containers:
            - name: manager
              env:
              - name: ISTIO_GATEWAY
                value: istio-system/kubeflow-istio-ingress-gateway-https
