# This workflow will build a docker container, publish it to Azure Container Registry, and deploy it to Azure Kubernetes Service using a helm chart.
#
# https://github.com/Azure/actions-workflow-samples/tree/master/Kubernetes
#
# To configure this workflow:
#
# 1. Set up the following secrets in your workspace:
#     a. REGISTRY_USERNAME with ACR username
#     b. REGISTRY_PASSWORD with ACR Password
#     c. AZURE_CREDENTIALS with the output of `az ad sp create-for-rbac --sdk-auth`
#
# 2. Change the values for the REGISTRY_NAME, CLUSTER_NAME, CLUSTER_RESOURCE_GROUP and NAMESPACE environment variables (below).
name: deploy
on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  CLUSTER_NAME: k8s-cancentral-02-covid-aks
  CLUSTER_RESOURCE_GROUP: k8s-cancentral-01-covid-aks
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # Run kfctl
    - name: kustomize
      uses: statcan/actions/kubectl@master
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        app: kfctl
        args: apply -f kfctl_k8s_istio.v1.0.1.yaml
      env:
        OIDC_PROVIDER: "${{ secrets.OIDC_PROVIDER }}"
        OIDC_REDIRECT_URI: "${{ secrets.OIDC_REDIRECT_URI }}"
        OIDC_AUTH_URL: "${{ secrets.OIDC_AUTH_URL }}"
        CLIENT_ID: "${{ secrets.CLIENT_ID }}"
        APPLICATION_SECRET: "${{ secrets.APPLICATION_SECRET }}"

    # Run kubectl
    - name: kubectl
      uses: statcan/actions/kubectl@master
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        args: -n kubeflow patch --type=json gateway kubeflow-gateway -p '[{\"op\":\"replace\",\"path\":\"/spec/selector/istio\",\"value\":\"ingressgateway-kubeflow\"}]'
      env:
        OIDC_PROVIDER: "${{ secrets.OIDC_PROVIDER }}"
        OIDC_REDIRECT_URI: "${{ secrets.OIDC_REDIRECT_URI }}"
        OIDC_AUTH_URL: "${{ secrets.OIDC_AUTH_URL }}"
        CLIENT_ID: "${{ secrets.CLIENT_ID }}"
        APPLICATION_SECRET: "${{ secrets.APPLICATION_SECRET }}"

    # Run kubectl
    - name: kubectl
      uses: statcan/actions/kubectl@master
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        args: apply -f patches/kubeflow.yml -f patches/istio
      env:
        OIDC_PROVIDER: "${{ secrets.OIDC_PROVIDER }}"
        OIDC_REDIRECT_URI: "${{ secrets.OIDC_REDIRECT_URI }}"
        OIDC_AUTH_URL: "${{ secrets.OIDC_AUTH_URL }}"
        CLIENT_ID: "${{ secrets.CLIENT_ID }}"
        APPLICATION_SECRET: "${{ secrets.APPLICATION_SECRET }}"

    # Run kubectl
    - name: kubectl
      uses: statcan/actions/kubectl@master
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        args: annotate mutatingwebhookconfigurations.admissionregistration.k8s.io admission-webhook-mutating-webhook-configuration certmanager.k8s.io/inject-ca-from=kubeflow/admission-webhook-cert --overwrite
      env:
        OIDC_PROVIDER: "${{ secrets.OIDC_PROVIDER }}"
        OIDC_REDIRECT_URI: "${{ secrets.OIDC_REDIRECT_URI }}"
        OIDC_AUTH_URL: "${{ secrets.OIDC_AUTH_URL }}"
        CLIENT_ID: "${{ secrets.CLIENT_ID }}"
        APPLICATION_SECRET: "${{ secrets.APPLICATION_SECRET }}"
