# This workflow will build a docker container, publish it to Azure Container Registry, and deploy it to Azure Kubernetes Service using a helm chart.
#
# https://github.com/Azure/actions-workflow-samples/tree/master/Kubernetes
#
# To configure this workflow:
#
# 1. Set up the following secrets in your workspace:
#     a. REGISTRY_USERNAME with ACR username
#     b. REGISTRY_PASSWORD with ACR Password
#     c. AZURE_CREDENTIALS with the output of `az ad sp create-for-rbac --sdk-auth`
#
# 2. Change the values for the REGISTRY_NAME, CLUSTER_NAME, CLUSTER_RESOURCE_GROUP and NAMESPACE environment variables (below).
name: deploy
on:
  release:
    types: [published]

# Environment variables available to all jobs and steps in this workflow
env:
  CLUSTER_NAME: k8s-cancentral-01-covid-aks
  CLUSTER_RESOURCE_GROUP: k8s-cancentral-01-covid-aks
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # Get Kubeconfig Context
    - name: Write Kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        mkdir -p /home/runner/work/_temp/_github_home/.kube
        echo "$KUBECONFIG" | base64 --decode > /home/runner/work/_temp/_github_home/.kube/config

    # Run Kustomize with kfctl
    - name: Kustomize
      uses: statcan/actions/kubeflow-manifest@master
      env:
        OIDC_PROVIDER: "${{ secrets.OIDC_PROVIDER }}"
        OIDC_REDIRECT_URI: "${{ secrets.OIDC_REDIRECT_URI }}"
        OIDC_AUTH_URL: "${{ secrets.OIDC_AUTH_URL }}"
        CLIENT_ID: "${{ secrets.CLIENT_ID }}"
        APPLICATION_SECRET: "${{ secrets.APPLICATION_SECRET }}"
